#!/bin/bash

	{
		s = 0; max = 0;

		for(i=2; i<NF; i++) {
			s+=$i
			if($i>max)
				max=$i
		}

		MAX[$1] = max
		AVG[$1] = s/(NF-1)
	}

	END {

		for(a in AVG) {
			if(MAX[a]>23)
				print a, AVG[a]
		}
	}

	GDB